"""
    Merge CRM API

    The unified API for building rich integrations with multiple CRM platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergeCRMClient
from MergeCRMClient.model.debug_mode_log import DebugModeLog
from MergeCRMClient.model.error_validation_problem import ErrorValidationProblem
from MergeCRMClient.model.opportunity import Opportunity
from MergeCRMClient.model.warning_validation_problem import WarningValidationProblem
globals()['DebugModeLog'] = DebugModeLog
globals()['ErrorValidationProblem'] = ErrorValidationProblem
globals()['Opportunity'] = Opportunity
globals()['WarningValidationProblem'] = WarningValidationProblem
from MergeCRMClient.model.opportunity_response import OpportunityResponse
from MergeCRMClient.api_client import ApiClient


class TestOpportunityResponse(unittest.TestCase):
    """OpportunityResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOpportunityResponse(self):
        """Test OpportunityResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OpportunityResponse()  # noqa: E501

        """
        No test json responses were defined for OpportunityResponse
        """
        raw_json = None

        if raw_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = raw_json

        deserialized = ApiClient().deserialize(response_mock, (OpportunityResponse,), False)

        assert deserialized is not None

        assert deserialized.model is not None
        assert deserialized.warnings is not None
        assert deserialized.errors is not None


if __name__ == '__main__':
    unittest.main()
